[package]
name = "ui"
version = "0.0.1"
authors = [ "Pants Build <pantsbuild@gmail.com>" ]

[lib]
path = "src/lib.rs"

[[bin]]
name = "demo"
path = "test/demo.rs"

[dependencies]
rand = "0.5.1"
termion = "1.5.1"
unicode-segmentation = "1.2.1"
